name: Test Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with coverage
      run: |
        npm run test:coverage -- --json --outputFile=test-results.json || true
        
    - name: Generate test report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Jest Test Results
        path: test-results.json
        reporter: jest-json
        
    - name: Comment PR with coverage
      if: always()
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        lcov-file: ./coverage/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Check coverage thresholds
      run: |
        # Extract coverage percentages
        COVERAGE=$(npx nyc report --reporter=text-summary | grep 'Statements' | awk '{print $3}' | sed 's/%//')
        
        # Set threshold (e.g., 80%)
        THRESHOLD=80
        
        if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
          echo "Coverage ${COVERAGE}% is below threshold ${THRESHOLD}%"
          exit 1
        else
          echo "Coverage ${COVERAGE}% meets threshold ${THRESHOLD}%"
        fi
      continue-on-error: true